vscode:
  extensions:
    - 2gua.rainbow-brackets@0.0.6:Tbu8dTz0i+/bgcKQTQ5b8g==
    - bungcip.better-toml@0.3.2:3QfgGxxYtGHfJKQU7H0nEw==
    - Equinusocio.vsc-material-theme@32.8.0:USk6zI85s3FXQT+pR/r2lA==
    - Prisma.vscode-graphql@0.2.35:57lo8i06VgXT8drY3ozz1g==
    - esbenp.prettier-vscode@5.5.0:xcEnHt0vYXkhJ8IkBmNAuA==
    - lkytal.FlatUI@1.4.9:5vec2u5gg2MBYMQGfj9Qiw==
    - Orta.vscode-jest@4.0.0-alpha.1:TuNngpN2TTsC/Ck1qhIwrg==
